### ISSUE TITLE
Add PyMC calendar

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc.io#12]
As we're opening our meetings to the public, we should add our calendar on the website: https://calendar.google.com/calendar/u/2?cid=cHltYy5kZXZzQGdtYWlsLmNvbQ

**Comment by reshamas** [comment]
It looks like right now, the permissions for the calendar need to be updated so it is publicly viewable.

@OriolAbril suggested putting a pointer to the calendar here: http://docs.pymc.io/
I wonder if we had a menu item called "Community" and then sub-items in this way:

Community
- Calendar
- Blog

cc: @cluhmann

**Comment by reshamas** [comment]
Can this issue be closed?

Calendar appears here:
https://www.pymc.io/community/calendar.html
