### ISSUE TITLE
Add URLs to YouTube & LinkedIn page on website

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc.io#2]
YouTube:  https://www.youtube.com/c/PyMCDevelopers
LinkedIn: https://www.linkedin.com/company/pymc/

cc:  @OriolAbril @mjhajharia @twiecki

**Comment by OriolAbril** [comment]
I didn't even know we had a linkedin :sweat_smile:. Thanks!

**Comment by OriolAbril** [comment]
Done in #4 for the pymc.io website (project info + blog) and in progress for the docs in https://github.com/pymc-devs/pymc/pull/5684
