### ISSUE TITLE
Add additional functionality such as SMC, Time Series etc

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc.io#20]
If were mentioning GPs maybe we should include other advanced functionality like SMC, Bart, Time Series etc. Not strictly required just mentioning it

![image](https://user-images.githubusercontent.com/7213793/169199670-65bcc96a-0d3e-4b46-bdff-671f3f7fac88.png)

**Comment by OriolAbril** [comment]
This is already taken care of in #14 I think
