### ISSUE TITLE
Write blog: announce GSoC people / projects

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc.io#23]
### PyMC Blog
[Meet our 2022 PyMC Google Summer of Code Students](https://www.pymc.io/blog/blog_gsoc_2022.html)

### People to add
- [x] Purna Chandra Mansingh
- [x] Larry Dong
- [x] Kunal Ghosh
- [x] Danh Phan
- [x] Shashank Kirtania
- [x] Conor Hassan
- [x] Yann McLatchie
- [x] Nicoleta Spînu #51 

### Reference
- https://twitter.com/tardis_sn/status/1529469086521905153

### Notes
@GoogleOSS

### Social Media
- Twitter:  https://twitter.com/pymc_devs/status/1544712019630227460?s=20&t=CQrjUlBIsweZFrAzStrPnQ

**Comment by OriolAbril** [comment]
Yes! That would be amazing. A possible template a bit more extended so interns can present themselves and/or their project would be something like https://numfocus.org/blog/meet-our-2019-gsoc-students-part-2 (not sure if this is still done in recent years, this is from 2019 when I participated)

**Comment by reshamas** [comment]
@BerylKanali
Closing this issue.
