### ISSUE TITLE
Add link to purchase swag under "Community" ?

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc.io#29]
Page:  https://www.pymc.io/community/index.html

https://numfocus.myspreadshop.com/pymc+official+logo?idea=61f03c1df33f941d0307b965

Add link to purchase swag under "Community" ?
Or is there a better place for it?

### Social links
- LinkedIn: https://www.linkedin.com/company/pymc/
- Twitter:  https://twitter.com/pymc_devs
- YouTube: https://www.youtube.com/@pymc-devs
- Meetup: https://www.meetup.com/pymc-online-meetup/
- Mastodon: https://bayes.club/@pymc

cc: @OriolAbril

**Comment by OriolAbril** [comment]
I would add a "support PyMC" page on the homepage sidebar, like ecosystem or testimonials, and there add the guidance on how to cite pymc, how to donate, how to buy swag, maybe also a link to the contributing guide.

**Comment by twiecki** [comment]
I would do both, I think people might want to buy swag even without wanting to support PyMC.

**Comment by BhaswatiRoy** [comment]
Hello @reshamas 
We can create a heading "Swags" under "community" section just like "discourse", "conference", "twitter" etc
![image](https://user-images.githubusercontent.com/78029145/214073424-facb86d0-3adc-4c4e-98f1-6554a7b54dc5.png)

**Comment by OriolAbril** [comment]
Thanks @BhaswatiRoy! Let us know if you need anything before sending the PR. I'd probably place the new "Swag" or "PyMC shop" (not sure what heading would be best) as the 3rd of the page, between conferences and twitter.

While we are modifying the community page, I'd also update the twitter section to be "Social media" and add links to all social media (twitter, mastodon, meetup and youtube).

**Comment by BhaswatiRoy** [comment]
Hello @OriolAbril 
apart from the swags section should I also change Twitter to social media and all the links there?

**Comment by OriolAbril** [comment]
If you can that would be great

**Comment by BhaswatiRoy** [comment]
Could you please send the mastodon & meetup links?
Also, can this link be added for youtube? https://www.youtube.com/@pymc-devs

**Comment by OriolAbril** [comment]
* meetup: https://www.meetup.com/pymc-online-meetup/
* mastodon: https://bayes.club/@pymc

> Also, can this link be added for youtube? https://www.youtube.com/@pymc-devs

yes, that is the youtube link you should use

**Comment by reshamas** [comment]
@BhaswatiRoy @OriolAbril 
For easy ref, I added these social media links to the issue description:  

### Social links
- LinkedIn: https://www.linkedin.com/company/pymc/
- Twitter:  https://twitter.com/pymc_devs
- YouTube: https://www.youtube.com/@pymc-devs
- Meetup: https://www.meetup.com/pymc-online-meetup/
- Mastodon: https://bayes.club/@pymc

**Comment by OriolAbril** [comment]
Thanks! I had completely forgotten about linkedin

**Comment by BhaswatiRoy** [comment]
Hello @reshamas @OriolAbril 
I came up with this. Would you suggest any changes?
![image](https://user-images.githubusercontent.com/78029145/214482419-7ee6afab-3ef5-436e-a6c0-aea37d8f7b51.png)

**Comment by BhaswatiRoy** [comment]
Hello @OriolAbril @reshamas 
Thanks for sending the links, I have submitted a pr. 
Do let me know if I need to make any changes.
