### ISSUE TITLE
Add link to PyMCon 2020 videos in Community/Conferences section 

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc.io#30]
https://www.pymc.io/community/index.html

Currently, the "Community/Conferences" section reads:
>The PyMC community organizes [PyMCon](https://pymc-devs.github.io/pymcon/), whose last edition was in 2020. Follow Discourse or Twitter to be updated about the next edition!

>PyMC talks have been given at a number of conferences, including [PyCon](https://us.pycon.org/), [PyData](https://pydata.org/events/), and [ODSC](https://odsc.com/) events.

#### Update suggestion:
The PyMC community organizes [PyMCon](https://pymc-devs.github.io/pymcon/), whose last edition was in 2020. Follow **[Discourse](https://discourse.pymc.io), [Twitter](https://twitter.com/pymc_devs), or [LinkedIn](https://www.linkedin.com/company/pymc/)** to be updated about the next edition! **The [PyMCon 2020 videos](https://www.youtube.com/c/PyMCDevelopers/videos) are available for viewing.**

PyMC talks have been given at a number of conferences, including [PyCon](https://us.pycon.org/), [PyData](https://pydata.org/events/), and [ODSC](https://odsc.com/) events.  **There is a [PyMC playlist](https://www.youtube.com/playlist?list=PL1Ma_1DBbE82OVW8Fz_6Ts1oOeyOAiovy) of talks available.**

cc: @twiecki 
FYI: Your playlist is entitled "PyMC3".  
Suggestion: (1) rename to "PyMC";  or (2) create two separate playlists: "PyMC3" and "PyMC"
https://www.youtube.com/playlist?list=PL1Ma_1DBbE82OVW8Fz_6Ts1oOeyOAiovy

**Comment by BhaswatiRoy** [comment]
Hello @reshamas 
I can work on adding the links!
