### ISSUE TITLE
Navbar is broken

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc.io#53]
Not sure if this is the right repo, but if I go to:
https://www.pymc.io/projects/docs/en/latest/contributing/index.html

From there, all links in the navbar are broken, e.g. Home links to:
https://www.pymc.io/projects/docs/en/latest/https:/www.pymc.io/welcome.html.html

**Comment by cluhmann** [comment]
@OriolAbril said:

>We should pin the theme back to 0.10.0 and open an issue on pydata sphinx theme
> Also maybe pin the theme version and update it manually as it is quite unstable and every release has broken something so far

and said that [this](https://github.com/pydata/pydata-sphinx-theme/issues/913) is what we are running into and that:

> it has an open PR already to fix the issue but I don't know how long it will take to merge and to have a new release. We should probably pin back to <0.10.0 in the meantime so the navbar works. Can someone do it?

**Comment by cluhmann** [comment]
That PR has been merged and is now sitting in version 0.12.0rc1 of the theme, FYI.

**Comment by reshamas** [comment]
@symeneses
For reference, here is a past PR where there was some pinning of the theme (Sep 2011):  
https://github.com/pymc-devs/pymc/pull/6120

**Comment by OriolAbril** [comment]
https://github.com/pymc-devs/pymc/pull/6296, https://github.com/pymc-devs/pymc-examples/pull/465, https://github.com/pymc-devs/pymc.io/pull/57 are fixing the issue for good and removing the need for 3 PRs whenever we do any theme related change.
