### ISSUE TITLE
Community page points to old site on PyMCon; let's point to new site

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc.io#58]
On this page:  
https://www.pymc.io/community/index.html

1) need to point to new PyMCon site:  
https://pymcon.com/

2) Let's include the hashtag here.

current
>The PyMC community organizes [PyMCon](https://pymc-devs.github.io/pymcon/), whose last edition was in 2020. Follow Discourse or Twitter to be updated about the next edition!

change to:
>The PyMC community organizes [PyMCon](https://pymcon.com/), whose last edition was in [2020](https://pymc-devs.github.io/pymcon/). Follow us on any or *all* platforms for updates:  Discourse, LinkedIn, YouTube and Twitter.  Our official hashtag is #pymcon.

**Comment by OriolAbril** [comment]
We should also update the announcement cards: https://www.pymc.io/welcome.html#announcements. cc @canyon289 @cuchoi @cluhmann

**Comment by cluhmann** [comment]
Good to close?

**Comment by OriolAbril** [comment]
The announcements in the landing page need to be updated too

**Comment by reshamas** [comment]
@cluhmann @OriolAbril 
Closing this issue and opened a new one, #64 
Information in comments for additional work (such as here) means it might be missed and it's easier to see the changes needed in a new issue.

It's also less daunting for new contributors who are submitting a simple PR, and we can avoid compounding their work. For new contributors, it is rewarding to be able to submit some small PRs.
