### ISSUE TITLE
write blog: [Keynote] PyMC: Past, Present, and Future

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc.io#63]
write summary blog:
video:  **[Keynote] PyMC: Past, Present, and Future (Chris Fonnesbeck)**
https://www.youtube.com/watch?v=RXODDVK7B-g

The timestamps are in the video description.  
Goal of this summary:  
- How would one explain the history of PyMC to a newcomer?  
- What is the roadmap from the beginning to current?
- etc.

cc:  @rowangayleschaefer

**Comment by fonnesbeck** [comment]
@reshamas sure, will send them to you on Slack

**Comment by OriolAbril** [comment]
We can also update the history page while we are at it: https://www.pymc.io/about/history.html

**Comment by rowangayleschaefer** [comment]
I currently have this as a draft in Notion but also accessible via this webpage https://www.notion.so/PyMC-Past-Present-and-Future-6f417921f92d463e895251459ef1d487

Would love to get some feedback on level of detail and general direction!

**Comment by BhaswatiRoy** [comment]
Hello, I work on the summarization.
Should I create a draft on google docs first and then get it reviewed?

**Comment by reshamas** [comment]
@BhaswatiRoy We do have a half-written blog.  
Will submit a PR or share otherwise so we do not duplicate the work.

**Comment by BhaswatiRoy** [comment]
> @BhaswatiRoy We do have a half-written blog. Will submit a PR or share otherwise so we do not duplicate the work.

Okay thanks for informing
