### ISSUE TITLE
Image of BDA book cover is broken

### ISSUE THREAD

**Issue by cluhmann** [pymc-devs/pymc.io#69]
In the "Books" subsection of the "Learn" tab (i.e., [here](https://www.pymc.io/projects/docs/en/stable/learn/books.html)), the image of the BDA book is broken.

![image](https://user-images.githubusercontent.com/39170995/210089800-622800d9-6076-429f-beaa-2eea9bd3935b.png)

**Comment by OriolAbril** [comment]
https://github.com/pymc-devs/pymc/blob/main/docs/source/learn/books.md?plain=1#L83 needs to be updated to a correct image (or a local one).

**Comment by cluhmann** [comment]
That link works just fine.  Not sure what's going on.

**Comment by twiecki** [comment]
@SangamSwadiK That would be great!

**Comment by PlayingData** [comment]
I think the image link has been broken. Can I fix this issue?

**Comment by twiecki** [comment]
That'd be great!

**Comment by PlayingData** [comment]
this issue's source file location(https://github.com/pymc-devs/pymc/blob/main/docs/source/learn/books.md?plain=1#L83) is that change http instead of https. It would fix this issue. 

Guide to me. How I fixed this issue from this repository to another repository?

**Comment by twiecki** [comment]
@PlayingData You need to make a pull request that changes the URL. Check out e.g. https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

**Comment by PlayingData** [comment]
I have done to add book cover page image to the documentation page on the [pymc](https://github.com/pymc-devs/pymc) repository.  I have submitted request for [PR](https://github.com/pymc-devs/pymc/pull/6683)

**Comment by twiecki** [comment]
Closed by https://github.com/pymc-devs/pymc/pull/6683.

**Comment by cluhmann** [comment]
Thanks @PlayingData !
