### ISSUE TITLE
Cross post sprint testimonial from Data Umbrella blog

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc.io#7]
We should update https://github.com/pymc-devs/pymc.io/blob/main/blog/sprint_testimonial.md with a summary and a link to https://blog.dataumbrella.org/sandra-sprints. The post is markdown (with the option to use MyST syntax as extensions too). 

I'm not really sure how to go about it cc @reshamas @symeneses

**Comment by reshamas** [comment]
@OriolAbril 
Here is an example of how I cross post blogs for scikit-learn:

Blog:  https://blog.scikit-learn.org

Example of cross posted blog:  https://blog.scikit-learn.org/events/behind-the-scenes/
a) Basically copy the first paragraph and then link to the main blog. 
b) Add image to this cross-posted blog

For scikit-learn, markdown example:
https://github.com/scikit-learn/blog/blob/main/_posts/2022-03-21-behind-the-scenes.md
