### ISSUE TITLE
Add code example to first page

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc.io#9]
@zaxtax made a great point that what he really liked about the documentation site is that it directly shows some code to give folks an idea. I think we should do that for the new main page as well. I think what it is is the most important info and should be at the top.

<img width="778" alt="image" src="https://user-images.githubusercontent.com/674200/165565680-ca874f57-c1a1-42d8-9d5b-34152dc6ae45.png">

maybe we could move this information further down for people who then want a bit more information.

**Comment by zaxtax** [comment]
Just to be more concrete, one thing I really like about https://docs.pymc.io/en/v3/ is it gets right to the point about what PyMC is for and shows some example code that's fairly straightforward.

**Comment by twiecki** [comment]
Even better would be to make it interactive via JupyterLite REPL https://blog.jupyter.org/jupyter-everywhere-f8151c2cc6e8
